api_packs:
    path: /packs/
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:listPacks

api_card:
    path: /card/{card_code}.{_format}
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:getCard
        _format: json
    requirements:
        _format: json

api_cards:
    path: /cards/
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:listCards

api_cards_pack:
    path: /cards/{pack_code}.{_format}
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:listCardsByPack
        _format: json
    requirements:
        _format: json|xml|xlsx|xls

api_decklist:
    path: /decklist/{decklist_id}.{_format}
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:getDecklist
        _format: json
    requirements:
        _format: json
        decklist_id: \d+

api_decklists_by_date:
    path: /decklists/by_date/{date}.{_format}
    methods: [GET]
    defaults:
        _controller: AppBundle:Api:listDecklistsByDate
        _format: json
    requirements:
        _format: json
        date: \d\d\d\d-\d\d-\d\d

user_info:
    path: /user/info
    defaults:
        _controller: AppBundle:User:info
