app_admin_tournament:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_tournament.yml"
    prefix:   /tournament

AppBundle_admin_cycle:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_cycle.yml"
    prefix:   /cycle

AppBundle_admin_pack:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_pack.yml"
    prefix:   /pack

AppBundle_admin_type:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_type.yml"
    prefix:   /type
 
AppBundle_admin_subtype:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_subtype.yml"
    prefix:   /subtype

AppBundle_admin_faction:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_faction.yml"
    prefix:   /faction

AppBundle_admin_card:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_card.yml"
    prefix:   /card

AppBundle_excel:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_excel.yml"
    prefix:   /excel

admin:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Admin:index

admin_find_user:
    path: /user/find
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:find

admin_find_user_process:
    path: /user/find_process
    methods: [POST]
    defaults:
        _controller: AppBundle:UserAdmin:process

admin_show_user:
    path: /user/show/{user_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:show
        
admin_user_locked_toggle:
    path: /user/toggle_locked/{user_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:toggleLocked
        
admin_user_decklists_show:
    path: /user/decklists/{user_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:decklists

admin_decklist_delete:
    path: /decklist/delete/{decklist_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:deleteDecklist
        
admin_user_comments_show:
    path: /user/comments/{user_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:comments

admin_comment_hidden_toggle:
    path: /comment/toggle_hidden/{comment_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:toggleHiddenComment

admin_comment_delete:
    path: /comment/delete/{comment_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:UserAdmin:deleteComment
        