app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin

app_api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix: /api

app_cards:
    resource: "@AppBundle/Resources/config/routing/cards.yml"
#    prefix:

app_deck:
    resource: "@AppBundle/Resources/config/routing/deck.yml"
    prefix: /deck

app_decklist:
    resource: "@AppBundle/Resources/config/routing/decklist.yml"
    prefix: /decklist

app_review:
    resource: "@AppBundle/Resources/config/routing/review.yml"
    prefix: /review

app_tag:
    resource: "@AppBundle/Resources/config/routing/tag.yml"
    prefix: /tag

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:index

donators:
    pattern: /donators
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:donators

decks_list:
    pattern: /decks
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:list

decklists_searchform:
    pattern: /decklists/search
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:search

decklists_list:
    pattern: /decklists/{type}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:list
        type: popular
        page: 1
    requirements:
        page: \d+

card_reviews_list:
    pattern: /reviews/{page}
    defaults:
        _controller: AppBundle:Review:list
        page: 1
    requirements:
        page: \d+

about:
    pattern: /about
    defaults:
        _controller: AppBundle:Default:about

apidoc:
    pattern: /apidoc
    defaults:
        _controller: AppBundle:Default:apidoc

rules:
    pattern: /rules
    defaults:
        _controller: AppBundle:Default:rules

ffg:
    pattern: /ffg
    defaults:
        _controller: AppBundle:Default:ffg
