AppBundle\Entity\Scenario:
    type: entity
    table: scenario
    manyToOne:
        campaign:
            targetEntity: Campaign
            inversedBy: scenarios
            joinColumn:
                name: campaign_id
                referencedColumnName: id
    manyToMany:
        encounters:
            targetEntity: Encounter
            inversedBy: scenarios
            joinColumn:
                name: encounter_id
                referencedColumnName: id
    oneToMany:
        user_scenarios:
            targetEntity: Userscenario
            orderBy: {'id':'ASC'}
            mappedBy: scenario
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        position:
            type: smallint
            nullable: true
    uniqueConstraints:
        scenario_code_idx:
            columns: [ code ]
                    
